### PR TITLE
fix #30 (image endpoint returns wrong size)

### LINKED ISSUE #30: /image/[userid]/ returns wrong size image
when going to `https://zpi.zeus.gent/image/[userid]?size=64` you would expect to receive a 64*64 image. however, you receive a 128x image.
when using `size=63` or lower you get a 64x image as expected.

this pattern repeats when using `size=128`: you receive a 256x image, but when using `size=127` you get a 128x image.
the same occurs when using `size=256`, and so on.

### PR DESCRIPTION
**Pull request by lolcatjpg**

### CODE REVIEW

File: src/handlers/image.rs [hunk 1]
```diff
@@ -33,7 +33,7 @@ impl ImageHandler {
         // get closest size that is bigger, or largest if none are bigger
```
Comment (redfast00) [inline src/handlers/image.rs:33]: die comment is nu fout

Comment (hannes-dev) [inline src/handlers/image.rs:33]:
```suggestion
        // get next larger size if size is not available, or largest if none are bigger
```

**Comment by lolcatjpg** [comment]
i commited the fix for the comment :)
